<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../WEB-INF/vue/taglib.jsp"%>
<html>
<head>
<%@ include file="../WEB-INF/vue/head.jsp"%>
<script language="Javascript"> 
function bascule(elem) 
{ 

etat=document.getElementById(elem).style.display; 
if(etat=="none"){document.getElementById(elem).style.display="block";} 
else{document.getElementById(elem).style.display="none";} 
} 
 
</script> 
</head>
<body>
<%@ include file="../WEB-INF/vue/menu.jsp" %>

	<div class="container">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4><b>Ajouter un site</b></h4>
			</div>
			<div class="panel-body">
				<div id="collapse1" class="panel-collapse collapse in">
					<div class="panel-body">
						<c:choose>
						<c:when test="${ !empty sessionScope.sessionSite }">
								<div class="col-sm-9 recadre">
									<div class="row">
    <div class='col-md-offset-2 col-md-8 text-center'>
    <h2>Récapitulatif</h2>
    </div>
  </div>
									<h3>Vous avez entré le site "<c:out value="${sessionScope.sessionSite.nomsite}" />"</h3>
									<c:if test="${ !empty sessionScope.sessionSecteur }">
										<h4>La liste de ses secteurs:</h4>
									</c:if>
									<c:forEach items="${sessionScope.sessionSite.getSecteurs()}" var="secteurs">
											<c:if test="${ secteurs.nomsect != null }">
												<ul class="api-list">
												<li><c:out value="${secteurs.nomsect}" /></li>
												
												<c:if test="${ !empty sessionScope.sessionVoie }">
												
													<c:forEach items="${secteurs.getVoies()}" var="voies">
														<ul>
														   <c:if test="${ voies.nom_voie != null }">
															<li><c:out value="${ voies.nom_voie}" /></li>
															</c:if>
														</ul>
													</c:forEach>
												</c:if>
												</ul>
											</c:if>
									</c:forEach>
								</div>
								<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
	
								<div class="form-group">
									 <div class="col-sm-5 text-center">
								
										<a href="<c:url value="AjoutSecteur"/>" >	<button type="button" onClick=""
												class="btn btn-default preview-add-button">Ajouter secteur
											</button></a>
										</div>
										</div>
								<c:choose>
									<c:when test="${ !empty sessionScope.sessionSecteur }">
									<div class="form-group">
									 <div class="col-sm-3 text-center">
									
										<a href="<c:url value="AjoutVoie"/>" >	<button type="button" onClick=""
												class="btn btn-default preview-add-button">Ajouter voie
											</button></a>
										</div>
										</div>
									</c:when>
									</c:choose>
									
											<c:choose>
									<c:when test="${ !empty sessionScope.sessionVoie}">
									<div class="form-group">
									 <div class="col-sm-3 text-center">
											<button type="button" onClick="bascule('finir');"
												class="btn btn-default preview-add-button">Valider
											</button>
										</div>
										</div>
									</c:when>
									</c:choose>
									<hr/>
							<div class="col-sm-12" id="finir" style="display: none; margin-top:65px">
							<form method="post" accept-charset="UTF-8" action="AjoutSiteSecteurVoie" >
								<div class="panel-body form-horizontal payment-form">
									<div class="form-group">
										<div class="col-sm-12 text-right">
											<button type="submit"
												class="btn btn-default preview-add-button">Enregistrer
												le site</button>
										</div>
									</div>
								</div>
								
								<p class="${empty form.erreurs ? 'succes' : 'erreur'}">${form.resultat}</p>
							</form>
						</div>
						
						<div class="col-sm-12" id="site" style="display:none" >
							<%@ include file="ajoutSite.jsp"%>
						</div>
						
						</c:when>
						<c:otherwise>
						<div class="col-sm-12" id="site" style="display:block" >
							<%@ include file="ajoutSite.jsp"%>
						</div>
						</c:otherwise>
						</c:choose>
						
		
						
						
					

					</div>
				</div>
			</div>

		</div>

	</div>
</body>
</html>